// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsHCQT8zj2VUjbcQ0-3TycKrjRII7WbyE',
    appId: '1:356188233439:web:06f7f13ed1b9d3dab1136a',
    messagingSenderId: '356188233439',
    projectId: 'picsapp1-323af',
    authDomain: 'picsapp1-323af.firebaseapp.com',
    storageBucket: 'picsapp1-323af.firebasestorage.app',
    measurementId: 'G-1BDKL73PE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyiMi-tJjaJPJ0x0ezJu07t8b2ByTcggE',
    appId: '1:356188233439:android:f4ee7f9a578b06dab1136a',
    messagingSenderId: '356188233439',
    projectId: 'picsapp1-323af',
    storageBucket: 'picsapp1-323af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCStNWHQHAsM_UQ7GTWVvcm80cIa-et-g8',
    appId: '1:356188233439:ios:3c2e989a0386a1abb1136a',
    messagingSenderId: '356188233439',
    projectId: 'picsapp1-323af',
    storageBucket: 'picsapp1-323af.firebasestorage.app',
    iosBundleId: 'com.example.picsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCStNWHQHAsM_UQ7GTWVvcm80cIa-et-g8',
    appId: '1:356188233439:ios:3c2e989a0386a1abb1136a',
    messagingSenderId: '356188233439',
    projectId: 'picsapp1-323af',
    storageBucket: 'picsapp1-323af.firebasestorage.app',
    iosBundleId: 'com.example.picsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsHCQT8zj2VUjbcQ0-3TycKrjRII7WbyE',
    appId: '1:356188233439:web:0565f2e668f45d31b1136a',
    messagingSenderId: '356188233439',
    projectId: 'picsapp1-323af',
    authDomain: 'picsapp1-323af.firebaseapp.com',
    storageBucket: 'picsapp1-323af.firebasestorage.app',
    measurementId: 'G-DWLYHS5QZX',
  );
}
